# Generated by Django 6.0.2 on 2026-04-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_event_rename_name_registration_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='dietary',
            field=models.CharField(choices=[('1', 'veggie'), ('2', 'normal'), ('3', 't-rex')], default='2', max_length=1),
        ),
    ]
