# Generated by Django 6.0.2 on 2026-04-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='feedback',
            name='message',
            field=models.CharField(default='', max_length=250),
        ),
    ]
